/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddExpenseRequest {
  'date' : Timestamp,
  'note' : string,
  'category' : string,
  'amount' : number,
}
export interface AnomalyReport {
  'categoryComparisons' : Array<CategoryComparison>,
  'averageExpense' : number,
  'dailySpending' : Array<DailySpending>,
  'expenseAnomalies' : Array<ExpenseAnomaly>,
}
export interface CategoryBreakdown { 'total' : number, 'category' : string }
export interface CategoryComparison {
  'priorMonthTotal' : number,
  'category' : string,
  'percentChange' : number,
  'currentMonthTotal' : number,
}
export interface DailySpending {
  'total' : number,
  'date' : bigint,
  'dayLabel' : string,
}
export interface DashboardStats {
  'monthlySpending' : number,
  'savingsProgressPercent' : number,
  'totalBalance' : number,
}
export interface Expense {
  'id' : ExpenseId,
  'date' : Timestamp,
  'note' : string,
  'category' : string,
  'amount' : number,
}
export interface ExpenseAnomaly {
  'expenseId' : bigint,
  'date' : bigint,
  'isHighAmount' : boolean,
  'category' : string,
  'amount' : number,
}
export type ExpenseId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'addExpense' : ActorMethod<[AddExpenseRequest], bigint>,
  'deleteExpense' : ActorMethod<[ExpenseId], boolean>,
  'getAnomalyReport' : ActorMethod<[], AnomalyReport>,
  'getCategoryBreakdown' : ActorMethod<[], Array<CategoryBreakdown>>,
  'getDailySpending' : ActorMethod<[], Array<DailySpending>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'listExpenses' : ActorMethod<[], Array<Expense>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];