/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const AddExpenseRequest = IDL.Record({
  'date' : Timestamp,
  'note' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ExpenseId = IDL.Nat;
export const CategoryComparison = IDL.Record({
  'priorMonthTotal' : IDL.Float64,
  'category' : IDL.Text,
  'percentChange' : IDL.Float64,
  'currentMonthTotal' : IDL.Float64,
});
export const DailySpending = IDL.Record({
  'total' : IDL.Float64,
  'date' : IDL.Int,
  'dayLabel' : IDL.Text,
});
export const ExpenseAnomaly = IDL.Record({
  'expenseId' : IDL.Nat,
  'date' : IDL.Int,
  'isHighAmount' : IDL.Bool,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const AnomalyReport = IDL.Record({
  'categoryComparisons' : IDL.Vec(CategoryComparison),
  'averageExpense' : IDL.Float64,
  'dailySpending' : IDL.Vec(DailySpending),
  'expenseAnomalies' : IDL.Vec(ExpenseAnomaly),
});
export const CategoryBreakdown = IDL.Record({
  'total' : IDL.Float64,
  'category' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'monthlySpending' : IDL.Float64,
  'savingsProgressPercent' : IDL.Float64,
  'totalBalance' : IDL.Float64,
});
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'date' : Timestamp,
  'note' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func([AddExpenseRequest], [IDL.Nat], []),
  'deleteExpense' : IDL.Func([ExpenseId], [IDL.Bool], []),
  'getAnomalyReport' : IDL.Func([], [AnomalyReport], ['query']),
  'getCategoryBreakdown' : IDL.Func(
      [],
      [IDL.Vec(CategoryBreakdown)],
      ['query'],
    ),
  'getDailySpending' : IDL.Func([], [IDL.Vec(DailySpending)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const AddExpenseRequest = IDL.Record({
    'date' : Timestamp,
    'note' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ExpenseId = IDL.Nat;
  const CategoryComparison = IDL.Record({
    'priorMonthTotal' : IDL.Float64,
    'category' : IDL.Text,
    'percentChange' : IDL.Float64,
    'currentMonthTotal' : IDL.Float64,
  });
  const DailySpending = IDL.Record({
    'total' : IDL.Float64,
    'date' : IDL.Int,
    'dayLabel' : IDL.Text,
  });
  const ExpenseAnomaly = IDL.Record({
    'expenseId' : IDL.Nat,
    'date' : IDL.Int,
    'isHighAmount' : IDL.Bool,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const AnomalyReport = IDL.Record({
    'categoryComparisons' : IDL.Vec(CategoryComparison),
    'averageExpense' : IDL.Float64,
    'dailySpending' : IDL.Vec(DailySpending),
    'expenseAnomalies' : IDL.Vec(ExpenseAnomaly),
  });
  const CategoryBreakdown = IDL.Record({
    'total' : IDL.Float64,
    'category' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'monthlySpending' : IDL.Float64,
    'savingsProgressPercent' : IDL.Float64,
    'totalBalance' : IDL.Float64,
  });
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'date' : Timestamp,
    'note' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func([AddExpenseRequest], [IDL.Nat], []),
    'deleteExpense' : IDL.Func([ExpenseId], [IDL.Bool], []),
    'getAnomalyReport' : IDL.Func([], [AnomalyReport], ['query']),
    'getCategoryBreakdown' : IDL.Func(
        [],
        [IDL.Vec(CategoryBreakdown)],
        ['query'],
      ),
    'getDailySpending' : IDL.Func([], [IDL.Vec(DailySpending)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };