/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CategoryComparison {
    priorMonthTotal: number;
    category: string;
    percentChange: number;
    currentMonthTotal: number;
}
export interface CategoryBreakdown {
    total: number;
    category: string;
}
export type Timestamp = bigint;
export interface AddExpenseRequest {
    date: Timestamp;
    note: string;
    category: string;
    amount: number;
}
export interface AnomalyReport {
    categoryComparisons: Array<CategoryComparison>;
    averageExpense: number;
    dailySpending: Array<DailySpending>;
    expenseAnomalies: Array<ExpenseAnomaly>;
}
export type ExpenseId = bigint;
export interface ExpenseAnomaly {
    expenseId: bigint;
    date: bigint;
    isHighAmount: boolean;
    category: string;
    amount: number;
}
export interface Expense {
    id: ExpenseId;
    date: Timestamp;
    note: string;
    category: string;
    amount: number;
}
export interface DashboardStats {
    monthlySpending: number;
    savingsProgressPercent: number;
    totalBalance: number;
}
export interface DailySpending {
    total: number;
    date: bigint;
    dayLabel: string;
}
export interface backendInterface {
    addExpense(req: AddExpenseRequest): Promise<bigint>;
    deleteExpense(id: ExpenseId): Promise<boolean>;
    getAnomalyReport(): Promise<AnomalyReport>;
    getCategoryBreakdown(): Promise<Array<CategoryBreakdown>>;
    getDailySpending(): Promise<Array<DailySpending>>;
    getDashboardStats(): Promise<DashboardStats>;
    listExpenses(): Promise<Array<Expense>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExpense(arg0: AddExpenseRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: ExpenseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async getAnomalyReport(): Promise<AnomalyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnomalyReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnomalyReport();
            return result;
        }
    }
    async getCategoryBreakdown(): Promise<Array<CategoryBreakdown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryBreakdown();
            return result;
        }
    }
    async getDailySpending(): Promise<Array<DailySpending>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySpending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySpending();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async listExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses();
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
